#!/bin/sh
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"

echo "Processing /etc/profile..."

# #id -un是打印输出当前的用户名,例如:root
USER="`id -un`"
LOGNAME=$USER

#通过/bin/hostname获取主机名
HOSTNAME=`/bin/hostname`

#登录后显示的控制台名称,与etc/issue相关?
#形如：“[用户名@主机名 目录]#”，\h引用了HOSTNAME,而在rcS里设置了/bin/hostname xxxx
# \h :仅取主机的第一个名字，例如xx.linux，则 \h=xx
export PS1='[\u@\h:\W]# '
#PS1="[$USER@$HOSTNAME \$PWD]#"

export USER LOGNAME HOSTNAME PS1

export FIRMWARE=/lib/firmware

export ALSA_CONFIG_PATH=/home/alsa/share/alsa/alsa.conf

sleep 3

echo "Processing /etc/profile..."
echo "we will run three script symbol three stage"
echo "some stage will waste a few minutes. don't shutdowm until finish!"

chmod a+x /home/*.sh
chmod a+x /home/mke2fs

/home/analy_install_or_recover.sh | tee /dev/tty0
