#!/bin/sh
#
case "$1" in
       start)
                /root/init_shell/ubi_mount_data.sh &
                ;;
        stop)
                ;;
        restart|reload)
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

